### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by dimanshu** [shivammalviya712/Real-Time-Trigger-Word-Detection#7]
Model is loaded
Realtime is done
start
yesssss
(array([ 0.00747681,  0.00985718,  0.01608276, ..., -0.00848389,
       -0.01101685, -0.0112915 ]), 44100)
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    realtime.refresh_audio()
  File "/home/dimanshu/Trigger-Word-Detection/code/realtime.py", line 41, in refresh_audio
    self.new_x = self.spectrogram(self.new_audio).T
  File "/home/dimanshu/Trigger-Word-Detection/code/realtime.py", line 63, in spectrogram
    nchannels = sound.ndim
AttributeError: 'tuple' object has no attribute 'ndim'

**Comment by dimanshu** [comment]
im getting this error while loading 10 sec audio wav file
